#page title
page_title                                : TremorCode                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                              # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.tc.bestquotes                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
website_icon                              : assets/logo.png
app_icon                                  : assets/Icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Life Quotes                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Think positive, stay strong and seize the day, share quotes on social media and more! Download our free app and get the most popular quotes.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.
 


# Information About Yourself
your_name                                 : TremorCode                               
your_link                                 : #https://tremorcode.github.io/                    
your_city                                 : #Serbia                                
email_address                             : tc_contact@yahoo.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Most popular quotes
    description                           : The most popular quotes, sayings and proverbs in one app. Carefully handpicked collection of most popular and most liked quotes.
    fontawesome_icon_name                 : quote-right
    
  - title                                 : Share with friends
    description                           : Share with your friends and share on social media with tap. 
    fontawesome_icon_name                 : share
    
  - title                                 : Famous authors
    description                           : Quotes from most famous authors and writers. 
    fontawesome_icon_name                 : fire-alt

  - title                                 : Favorite quotes
    description                           : Create your own list with your favorite quotes. Find your favorite quotes easy and share them on social media.
    fontawesome_icon_name                 : heart

  - title                                 : Quote editor and creator
    description                           : Create, edit and share quote as image, edit to your own liking, set as wallpaper, share on social media or save on your device.
    fontawesome_icon_name                 : image

  - title                                 : 30+ unique categories and over 1000 quotes
    description                           : Browse 30 unique categories with unique quotes.
    fontawesome_icon_name                 : list-ol
  
  - title                                 : 100% free
    description                           : You can download this app for free on Play Store. Everything is unlocked and available.
    fontawesome_icon_name                 : download

  - title                                 : Fully optimized
    description                           : Optimized to work on 99% devices. 
    fontawesome_icon_name                 : tablet

  - title                                 : Work's offline
    description                           : Browse all quotes offline anytime anywhere you are. No internet connection is required.
    fontawesome_icon_name                 : wifi

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#FFFFFF"

cover_image                               : assets/headerimage.png                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f1f1f1"

link_color                                : "#4584f0"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

 











####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
